# Helmfile configuration for grounds-dev
# Orchestrates deployment of PostgreSQL and Agones
# Uses declarative approach with proper dependency management

# Helm repositories
repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: agones
    url: https://agones.dev/chart/stable

# Helm releases in deployment order
releases:
  # PostgreSQL database for application data
  - name: postgresql
    namespace: databases
    chart: bitnami/postgresql
    version: "~18"  # Use PostgreSQL 18.x (latest stable)
    values:
      - values/postgresql.values.yaml
    # Wait for PostgreSQL to be ready before proceeding
    wait: true
    timeout: 300

  # Agones game server hosting platform
  - name: agones
    namespace: games
    chart: agones/agones
    # Use latest stable version (no version pinning for Agones)
    values:
      - values/agones.values.yaml
    # Wait for Agones controller to be ready
    wait: true
    timeout: 300
    # Install CRDs automatically
    createNamespace: false

