apiVersion: k3d.io/v1alpha5
kind: Simple
metadata:
  name: dev

# Cluster topology: 1 server (control plane) + 2 agents (worker nodes)
servers: 1
agents: 2

image: rancher/k3s:v1.34.1-k3s1

# Port mappings for ingress traffic
ports:
  - port: 80:80    # HTTP ingress - accessible via localhost:80
    nodeFilters: [server:0]
  - port: 443:443  # HTTPS ingress - accessible via localhost:443
    nodeFilters: [server:0]

# Integrated registry for local image development
registries:
  create:
    name: dev-registry
    host: 0.0.0.0
    hostPort: "5001"
  config: |
    mirrors:
      "docker.io":
        endpoint:
          - "https://mirror.gcr.io"
      "https://registry-1.docker.io":
        endpoint:
          - "https://mirror.gcr.io"
    configs:
      "docker.io":
        auth:
          username: ${DOCKER_USERNAME}
          password: ${DOCKER_PASSWORD}

options:
  k3d:
    wait: true  # Wait for cluster to be ready before returning
